# .streamlit/config.toml

[theme]
primaryColor = "#ffffff"             # White 
backgroundColor = "#000000"          # Black
secondaryBackgroundColor = "#111827" # Dark black
textColor = "#ffffff"                # White
font = "monospace"        # Clean, readable, modern
